// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHKTD9rr2LA7SSH7rTa_iJbbWwHznLy7Y',
    appId: '1:408184381219:web:97b9582efa637bd9463696',
    messagingSenderId: '408184381219',
    projectId: 'sptd-lms',
    authDomain: 'sptd-lms.firebaseapp.com',
    storageBucket: 'sptd-lms.appspot.com',
    measurementId: 'G-0470SQ4NPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTeDs52yR-S_eciDUD5acdXJ6tz9DHJI0',
    appId: '1:408184381219:android:3f9342e046ae70ea463696',
    messagingSenderId: '408184381219',
    projectId: 'sptd-lms',
    storageBucket: 'sptd-lms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwJ3SkMnAqNiZ3VW3UYuDXrIj3xlvrIlY',
    appId: '1:408184381219:ios:52e202e64521d77b463696',
    messagingSenderId: '408184381219',
    projectId: 'sptd-lms',
    storageBucket: 'sptd-lms.appspot.com',
    iosClientId: '408184381219-6s56q1jaoihjq3gne2ehm7g51mq0jd99.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwJ3SkMnAqNiZ3VW3UYuDXrIj3xlvrIlY',
    appId: '1:408184381219:ios:52e202e64521d77b463696',
    messagingSenderId: '408184381219',
    projectId: 'sptd-lms',
    storageBucket: 'sptd-lms.appspot.com',
    iosClientId: '408184381219-6s56q1jaoihjq3gne2ehm7g51mq0jd99.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementSystem',
  );
}
