// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAARh3Y2j_KScVUVDeKpSgVhZYgtAvQl0E',
    appId: '1:1018897764585:web:a3b97b659d746d2f772078',
    messagingSenderId: '1018897764585',
    projectId: 'fir-flutter-codelab-234ee',
    authDomain: 'fir-flutter-codelab-234ee.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-234ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGss01MMAA2q7Pwv1M4yozXf5y6X94JRI',
    appId: '1:1018897764585:android:e1e55f471e1a536c772078',
    messagingSenderId: '1018897764585',
    projectId: 'fir-flutter-codelab-234ee',
    storageBucket: 'fir-flutter-codelab-234ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KueRuTZMdxQOlvwvzDCjvBzIQeb3z10',
    appId: '1:1018897764585:ios:382c450eb3d87b20772078',
    messagingSenderId: '1018897764585',
    projectId: 'fir-flutter-codelab-234ee',
    storageBucket: 'fir-flutter-codelab-234ee.appspot.com',
    iosClientId: '1018897764585-ge4lmlt6ue1gv3t15qqigt7qkjr3juph.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KueRuTZMdxQOlvwvzDCjvBzIQeb3z10',
    appId: '1:1018897764585:ios:382c450eb3d87b20772078',
    messagingSenderId: '1018897764585',
    projectId: 'fir-flutter-codelab-234ee',
    storageBucket: 'fir-flutter-codelab-234ee.appspot.com',
    iosClientId: '1018897764585-ge4lmlt6ue1gv3t15qqigt7qkjr3juph.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
